"use client";

import { memo } from "react";
import { Handle, Position, type Node, type NodeProps } from "@xyflow/react";
import type { AnalysisNodeData } from "@/store/useAnchorStore";
import { HANDLE_CLASS, RISK_STYLES } from "./nodeStyles";

type AnalysisNodeType = Node<AnalysisNodeData, "analysis">;

/**
 * AnalysisNode (blue) — Alexa+ comparing the trigger to the user's anchors.
 * Names the distortion, rates the risk, shows the matched anchor. Switches to a
 * red "act now" treatment when the analysis flags a genuine safety signal.
 */
function AnalysisNodeImpl({ data }: NodeProps<AnalysisNodeType>) {
  const risk = RISK_STYLES[data.risk];
  const genuine = data.genuineRisk;
  const accent = genuine ? "#ef4444" : "#3b82f6";

  return (
    <div
      className="w-[360px] max-w-[86vw] rounded-2xl border-2 bg-white p-5 shadow-lg dark:bg-slate-900/90"
      style={{ borderColor: accent }}
    >
      <Handle type="target" position={Position.Top} className={HANDLE_CLASS} />

      <div className="flex items-center gap-2.5">
        <span
          className="flex h-8 w-8 items-center justify-center rounded-full text-white"
          style={{ backgroundColor: accent }}
          aria-hidden
        >
          <svg
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            className="h-5 w-5"
          >
            <path d="M12 2a7 7 0 0 0-4 12.7V17a2 2 0 0 0 2 2h4a2 2 0 0 0 2-2v-2.3A7 7 0 0 0 12 2z" />
            <path d="M9 22h6" />
          </svg>
        </span>
        <span
          className="text-sm font-bold uppercase tracking-widest"
          style={{ color: accent }}
        >
          {genuine ? "Reality check" : "Alexa+ analysis"}
        </span>
        <span
          className={[
            "ml-auto rounded-full px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide",
            data.source === "model"
              ? "bg-indigo-100 text-indigo-700 dark:bg-indigo-500/20 dark:text-indigo-300"
              : "bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-400",
          ].join(" ")}
          title={
            data.source === "model"
              ? "Generated by the real model"
              : "Offline heuristic fallback (dev/test)"
          }
        >
          {data.source === "model" ? "AI" : "heuristic"}
        </span>
      </div>

      {genuine ? (
        <>
          <p className="mt-3 text-2xl font-extrabold leading-tight text-red-600 dark:text-red-300">
            This is a real safety signal.
          </p>
          <p className="mt-2 text-base leading-snug text-slate-700 dark:text-slate-200">
            {data.rationale}
          </p>
          <div className="mt-4 rounded-xl bg-red-50 px-4 py-3 ring-1 ring-red-500/40 dark:bg-red-500/15">
            <p className="text-base font-semibold text-red-700 dark:text-red-200">
              This is not the loop — act now. Turn it off, get out, and call for
              help.
            </p>
          </div>
        </>
      ) : (
        <>
          <div className="mt-3 flex items-center justify-between gap-3">
            <p className="text-2xl font-extrabold leading-tight text-slate-900 dark:text-slate-50">
              {data.distortion}
            </p>
            <span
              className={`shrink-0 rounded-full px-3 py-1 text-sm font-bold ${risk.pill}`}
            >
              {risk.label}
            </span>
          </div>

          <p className="mt-2 text-base leading-snug text-slate-600 dark:text-slate-300">
            {data.rationale}
          </p>

          {data.matchedRule && (
            <div className="mt-4 rounded-xl bg-blue-50 px-4 py-3 ring-1 ring-blue-500/30 dark:bg-blue-500/10">
              <p className="text-xs font-bold uppercase tracking-widest text-blue-600 dark:text-blue-300">
                Your anchor
              </p>
              <p className="mt-1 text-base font-medium leading-snug text-slate-800 dark:text-slate-100">
                {data.matchedRule}
              </p>
            </div>
          )}
        </>
      )}

      {!genuine && (
        <Handle
          type="source"
          position={Position.Bottom}
          className={HANDLE_CLASS}
        />
      )}
    </div>
  );
}

export const AnalysisNode = memo(AnalysisNodeImpl);
